### PR TITLE
Ruby: add easy exercise after twofer

### PR DESCRIPTION
**Pull request by F3PiX**

### CODE REVIEW

**Comment by Insti** [comment]
@F3PiX do you have merge permission here yet?
If you do you can merge this. :heart:

**Comment by Insti** [comment]
Congratulations. :tada:

**Comment by F3PiX** [comment]
Thanks ;-) However, I still can't download this exercise 🤔 Do I need to change something else too?

**Comment by F3PiX** [comment]
Aha, thanks for enlightening me!

**Pull request merged**
