### PR TITLE
Add Github Actions workflows

### PR DESCRIPTION
**Pull request by kotp**
This is a solution to testing #1047 

Applied the patch so that it could be on this repository directly.

### CODE REVIEW

**Comment by kotp** [comment]
Getting:

```
The workflow is not valid. .github/workflows/exercise-tests.yml (Line: 55, Col: 21): Unrecognized named-value: 'test-arch'. Located at position 1 within expression: test-arch
```

for the action @cmccandless

**Comment by cmccandless** [comment]
I plan to validate this and workflows from other tracks using the nektos/act project. However, it's late in my timezone, so I'll do so in the morning.

**Comment by kotp** [comment]
> I plan to validate this and workflows from other tracks using the nektos/act project. However, it's late in my timezone, so I'll do so in the morning.

I was aware that it was getting close to midnight thirty for you… no worries.

**Comment by kotp** [comment]
Closing in favor of #1047

**Pull request closed without merging**
