### PR TITLE
Add tests for non-square matrix

### PR DESCRIPTION
**Pull request by goalaleo**
I mentored a solution which relied on the matrixes to be size 3x3 or 2x2. While this doesn't test matrixes of all sizes, it adds tests for a non-square matrix of size 2x3

Related solution:
https://exercism.io/mentor/solutions/c06d5e96459b407495564e6de2fbf6ec

### CODE REVIEW

**Comment by kotp** [comment]
Do you think this should be elevated to canonical at some point?

**Comment by goalaleo** [comment]
mm, probably? I can see this being relevant to all tracks, but to be honest
I'm not sure what the process is for adding new specifications.

Are all parts of the specifications shared between tracks? Can the specification be changed before the tests (for each track) are added?

**Comment by kotp** [comment]
> mm, probably? I can see this being relevant to all tracks, but to be honest
> I'm not sure what the process is for adding new specifications.

To introduce the change we would [open an issue on problem-specifications](https://github.com/exercism/problem-specifications/issues) to talk about it, and once discussed, open a PR there that makes the change.


> Are all parts of the specifications shared between tracks? Can the specification be changed before the tests (for each track) are added?

The specifications are specifically to share between the tracks, and some tracks remove things that may not be applicable to their tracks, and like is done here, some tracks add some things that may be relevant to that specific track.

**Comment by kotp** [comment]
To go a bit further, this track, has test generators that exist, that when set up, can use the specification data to generate the tests that we use.  Look at [generated test suites](https://github.com/exercism/ruby#generated-test-suites) which will get you started on what is used to generate the test, and looking at [implmementing a generator](https://github.com/exercism/ruby#implementing-a-generator) for information on how to do this.

**Comment by goalaleo** [comment]
Thanks @kotp I'll take a look at those 👍

**Pull request closed without merging**
