### PR TITLE
Grade school

### PR DESCRIPTION
**Pull request by NickEdwin**
Solved.

### CODE REVIEW

**Comment by kotp** [comment]
Solved what?  Not sure how this helps the project.  What is the goal?  What can we help you with?

**Comment by NickEdwin** [comment]
Sorry that PR was meant for my own branch and closed instantly. Sorry to
bother!

**Comment by NickEdwin** [comment]
Sorry that PR was meant for my own branch and closed instantly. Sorry to
bother!

**Comment by kotp** [comment]
Definitely ok.

**Pull request closed without merging**
