### PR TITLE
Match ruby version with test runner

### PR DESCRIPTION
**Pull request by meatball133**
The test runner uses 3.3.0 so makes no sense the track uses 3.2

### CODE REVIEW

**Comment by iHiD** [comment]
Seems sensible to me :)

**Review by iHiD — APPROVED** [review]

**Review by kotp — COMMENTED** [review]
So should we update the test runner to version 3.3.2 or reduce the version here?  It seems that we are going backward, and eventually we are likely going to be reverting this change.

**Review by kotp — APPROVED** [review]
My eyes misread, when I ran the audio, doh!  Yeah, definitely approved.

**Comment by meatball133** [comment]
I wrote my message wrong I meant to say 3.3

**Pull request merged**
