### PR TITLE
Sync all practice exercise docs

### PR DESCRIPTION
**Pull request by kytrinyx**
This updates all the descriptions for the practice exercises based on the changes in the problem specification.

Most (but not all) of the changes are implementing the one-sentence-per-line formatting, as well as moving inline links to be reference links.

If there are specific exercises that you think we should not update until we also update the tests, let me know and I'll remove them from this PR.

### CODE REVIEW

**Review by kotp — APPROVED** [review]
Not sure about the question about "merge before test updates", though.

**Comment by kytrinyx** [comment]
How about if I remove docs changes for the exercises where there are test changes to make?

**Comment by kytrinyx** [comment]
Having thought about this a bit, I think that I prefer to update only the docs for exercises that don't have any pending test updates.

I'm going to remove changes for those exercises from this PR.

**Comment by kytrinyx** [comment]
That removed the changes to 70 exercises, leaving instructions changed for 118 exercises.

**Comment by kotp** [comment]
Good choice!  Otherwise, the "update exercise" irritant will happen twice, and once only for formatting, rather than test updates and formatting and content.

**Pull request merged**
