### PR TITLE
Try to fix CI

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@kotp I've upgraded a bunch of stuff, but now I'm getting a different error. Would you mind looking into it?

**Comment by kotp** [comment]
Spent quite some time researching.

Without any success so far for a fix.

But pushing to see if the CI passes with this change...

**Comment by kotp** [comment]
The last commit does fix the knapsack, I think, but fails for where Data is being used for the zebra exercise.

**Comment by ErikSchierboom** [comment]
> The last commit does fix the knapsack, I think, but fails for where Data is being used for the zebra exercise.

Any chance you could fix that too?

**Comment by kotp** [comment]
> > The last commit does fix the knapsack, I think, but fails for where Data is being used for the zebra exercise.
> 
> Any chance you could fix that too?

Ruby 3.0 has just transitioned to End of Life, Ruby 3.1 will be end of life in the next 11 months.  Perhaps we make this "reportive" rather than required?

**Comment by kotp** [comment]
Thank you @ErikSchierboom !

**Comment by ErikSchierboom** [comment]
You too!

**Pull request merged**
