### PR TITLE
Fix grammar in chess-game's README

### PR DESCRIPTION
**Pull request by sid-707**

### CODE REVIEW

**Review by iHiD — APPROVED** [review]

**Comment by kotp** [comment]
@sid-707 Any reason to not have this set "Ready for review" so that it is not in "Draft" mode?

**Review by kotp — APPROVED** [review]

**Comment by sid-707** [comment]
Thank you for approving my PR @iHiD and @kotp.

Unfortunately, I can't merge it since GitHub says `Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.`

Feel free to merge it whenever you can.

**Comment by sid-707** [comment]
> @sid-707 Any reason to not have this set "Ready for review" so that it is not in "Draft" mode?

I was unsure about the process. I hadn't posted in the forum before making this PR so I left it in "Draft". I thought I'm supposed to make a PR only after receiving feedback in the forum.

**Comment by kotp** [comment]
It's all good, I only wanted to ensure that I did not change it from draft to ready for review if you were not ready for it.  But yes, generally we want to discuss changes in the forums, and then link to the PR, to proceed once we get the go ahead.

Thank you for the work!

**Comment by iHiD** [comment]
> I thought I'm supposed to make a PR only after receiving feedback in the forum.

You are, but we don't really distinguish between draft and normal PRs in that sense. Mainly a draft PR is someone demonstrating work that's been preagreed to show progress.

Either way, thank you for trying to follow the guidance. It's very much appreciated! :)

**Pull request merged**
