### PR TITLE
change: generate readme.md

### LINKED ISSUE #769: change: generate readme.md
This exercise is missing a `README.md` file in the exercise directory.
The Readme should be generated using the `configlet` tool.

### LINKED ISSUE #771: documentation: Update Readmes instructions.
The documentation in the repository README about exercise README.md files is out of date:

https://github.com/exercism/ruby#readmes

**to do:**

Update the [Ruby repository README](https://github.com/exercism/ruby/blob/master/README.md) with the information that: 

All exercises should have a README.md file.
This file should be generated using the `configlet` tool.
Probably some command line examples on how to do this.

### PR DESCRIPTION
**Pull request by njbbaer**
Resolves #769

### CODE REVIEW

**Comment by Insti** [comment]
Excellent! 

Were you able to work out how to run `configlet` without much trouble?

**Comment by njbbaer** [comment]
Yes. #771 explained it. I may go ahead and update the documentation for it too.

**Comment by kotp** [comment]
Thank you very much @njbbaer, sorry for the long delay.

**Comment by njbbaer** [comment]
Happy to contribute. Take a look at my other pull requests when you can.

**Pull request merged**
