### PR TITLE
Reformat 'about' documentation for nextercism

### PR DESCRIPTION
**Pull request by iHiD**
Hello. I'm trying to get all of the ABOUT.md files reformatted to fit with the new look and feel of nextercism. This means removing things like line-breaks and markdown that we're not supporting.

As an example from the C++ Track, we've gone from:
screen shot 2017-08-06 at 15 16 34
to
screen shot 2017-08-06 at 15 15 43

As a general note, after these formatting changes get merged, we're hoping that track
maintainers will take some time to review the contents of the ABOUT.md file and edit
it to make it a bit shorter and more casual. We're looking for less wikipedia and more
of an enthusiastic and friendly pitch that you might make to a friend over a drink for
why they should try the language.

For some examples of tracks where I think they've done this well take a look at the
Go and R tracks:
- https://github.com/exercism/go/blob/master/docs/ABOUT.md
- https://github.com/exercism/r/blob/3f05539d19d7e20d2a9d5cd2cecd3dc56f4f23e8/docs/ABOUT.md

See https://github.com/exercism/meta/issues/84 for more details.

Thank you!

### CODE REVIEW

**Comment by kotp** [comment]
Which and what subset of markdown is being supported?  I notice in the change there is still markdown for the link.

**Comment by iHiD** [comment]
> Which, and what subset of, markdown is being supported?

@kotp The canonical answer for that is going to be in the meta issue (as it might update based on the discussion we're having there about the last point) but for now it is: "ABOUT.md should now only use bold, italic, links, bullet lists and number lists, and should not split paragraphs into lines."

**Comment by kotp** [comment]
Yep, found it, and made my objection, though Nobbz beat me to it. :)

**Comment by iHiD** [comment]
> The markdown links should go too, according to this "only use" list, or be added to that list.

Links are there after italic.

**Comment by kotp** [comment]
:blush: yes, I see it now.

**Pull request merged**
