### PR TITLE
Add Github Actions workflows

### LINKED ISSUE #1045: Moving from Travis to GitHub Actions
Hello 🙂 

Over the last few months we've been transferring all our CI from Travis to [GitHub Actions (GHA)](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions). We've found that GHA are easier to work with, more reliable, and much much faster. 

Based on our success with GHA and increasing intermittent failures on Travis, we have now decided to try and remove Travis from Exercism's org altogether and [shift everything to GHA](https://github.com/exercism/exercism/issues/5396). This issue acts as a call to action if your track is still using Travis. 

For most CI checks this should be a transposing from Travis' syntax to [GHA syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions), and hopefully quite straightforward (see [this PR for an example](https://github.com/exercism/csharp/pull/1338/files)).  However, if you do encounter any issues doing this, please ask on Slack where lots of us now have experience with GHA, or post a comment here and I'll tag relevant people. This would also make a good Hacktoberfest issue for anyone interested in making their first contribution 🙂 

If you've already switched this track to GHA, please feel free to close this issue and ignore it.

Thanks!

### PR DESCRIPTION
**Pull request by cmccandless**
Resolves #1045 

These workflows will not run unless they already exist in the target branch because they are from a fork. Once this is merged and verified, all references to Travis CI (.travis.yml, badge in README, etc) should be removed in an additional PR.

### CODE REVIEW

**Review by kotp — APPROVED** [review]
LGTM

**Comment by kotp** [comment]
Did you want to prepare the expected PR?  So when this comes in, we can then verify and bring the second one in as well?

**Comment by kotp** [comment]
> These workflows will not run unless they already exist in the target branch because they are from a fork.

I provided #1048 because I was curious if the GHA would work if they were directly on the repository, rather than on a fork, including the genesis commit for the configuration.  Can you look at it and verify?

**Review by kotp — CHANGES_REQUESTED** [review]
See #1048 the GHA seems to be failing.

**Comment by cmccandless** [comment]
That will teach me to commit when low on sleep. I had done a similar PR for the `go` track, and had used the `julia` workflow as a starting point. Seems the `go` one still had a `julia` reference, and I completely forgot to change the test matrix for this track. This should be better.

Thanks to your test patch, the workflows are running here. As I'm typing this, I'm already seeing a failure, so I'll look into it.

**Comment by cmccandless** [comment]
Something's wrong with the caching, but without it, the builds are already quite fast. I would recommend merging without it for now, and can add via PR later.

Also, the `windows` test failed, but you weren't previously testing for Windows, so is that a deal breaker?

**Comment by cmccandless** [comment]
Huh, fixed Ruby version pinning (Travis was running 2.5, but I suspect you may want to run something newer like 2.7), and now macOS fails as well.

I'm going to leave this PR in the following state:
- caching disabled (to be added via follow-up PR)
- windows and macOS builds disabled (to be added via follow-up PR)

**Comment by cmccandless** [comment]
This should be ready to merge, unless there's any other changes you'd like to request.

**Review by kotp — APPROVED** [review]
Looks good.

**Pull request merged**
