### PR TITLE
meetup: rewrite tests and example implementation to align with README

### PR DESCRIPTION
**Pull request by nwallace**

### CODE REVIEW

**Comment by nwallace** [comment]
Here's an attempt to fix #761 . The README gives examples like "the Wednesteenth of January 2017", but the syntax I'm specifying in these tests is of the form "Teenth Wednesday of January, 2017". Is that right, or should it be "Wednesteenth"?

**Comment by Insti** [comment]
Hi @nwallace thanks for taking this on :heart:

It should be "wednesteenth", those crazy words are one of the "features" of this this exercise.

There is currently a pull request open to clarify the description of this problem:
https://github.com/exercism/problem-specifications/pull/982
You probably should bare those in mind while working on this.

**Comment by Insti** [comment]
This is looking good and is definitely on the right track 👍 

You will also need to update [the example solution](https://github.com/exercism/ruby/blob/master/exercises/meetup/.meta/solutions/meetup.rb) to pass the new test suite.

**Comment by Insti** [comment]
The description changes have now been merged: https://github.com/exercism/problem-specifications/blob/master/exercises/meetup/description.md

**Pull request closed without merging**
