### PR TITLE
[WIP] Implement exercise sublist

### PR DESCRIPTION
**Pull request by rnice01**
## Why?
This is not currently available in the Ruby track

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or enhancement that would cause existing functionality to change)
- [ ] Gardening (code and/or documentation cleanup)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change relies on a pending issue/pull request
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Insti** [comment]
Let us know if you have any questions or need any help @rnice01 
We can also be found in the gitter chat room: https://gitter.im/exercism/ruby

**Comment by Insti** [comment]
How are you getting on with this @rnice01? Need any help?

**Comment by rnice01** [comment]
Hey @Insti thanks for checking in, I think I'm ok for now. I have gotten busy with work and my family, so I'm hoping to get more progress this week.

**Comment by Insti** [comment]
There's been no progress on this for a while so I'm going to close it.

Feel free to open it again if you've made progress and want to continue, otherwise we'll leave it available for someone else to implement.

**Pull request closed without merging**
