### PR TITLE
[Fix]: Typo in test case

### PR DESCRIPTION
**Pull request by meatball133**

### CODE REVIEW

**Comment by kotp** [comment]
Is this already in place and merged from #1613 ?

**Comment by meatball133** [comment]
Yeah, thought there was no other pr about it. Since the user that opened that pr also opened a post on the forum without mentioning that they had opened a pr.

**Comment by vmyts539** [comment]
@meatball133, welp, sorry about that, It was a surprise for me that it was reopened and merged as I saw that it has closed automatically and you responded on the forum that you'll take it afterward so I thought that mine would just stay as it is

**Comment by kotp** [comment]
> @meatball133, welp, sorry about that, It was a surprise for me that it was reopened and merged as I saw that it has closed automatically and you responded on the forum that you'll take it afterward so I thought that mine would just stay as it is

I think it is just because message of "You can use this link to copy this into a new topic on the forum. If we decide the PR is appropriate, we'll reopen it and continue with it, so please don't delete your local branch." is late since it shows after you create the PR, and if you create the PR using command line tools, it is even more likely you will not see it in a timely manner.

So, @vmyts539 , more of a "Our Fault" problem than anything you did or did not do.

**Pull request closed without merging**
