### PR TITLE
Sync all-your-base with problem-specifications

### PR DESCRIPTION
**Pull request by kytrinyx**
There are no test changes; just docs.

### CODE REVIEW

**Review by kotp — CHANGES_REQUESTED** [review]
Perhaps use code block instead?  Or 4 space indent (no language highlighting then) to avoid reading this in plain text with the escaped asterisks.

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
I think this gets fixed with recent changes in Problem Specifications.

**Comment by kotp** [comment]
Will this need a "re-sync" @kytrinyx ?

**Comment by kytrinyx** [comment]
Indeed! I've re-synced, and force pushed.

**Pull request merged**
