### PR TITLE
Fix typo in Ruby numbers introduction

### PR DESCRIPTION
**Pull request by Auk14HP**

### CODE REVIEW

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
I added a change to try to get `configlet` to trigger finally, after two days.  It still said "Waiting for status to be reported" after 2 days.

If it still does not run I will see what I can see sometime this week.

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
@ErikSchierboom Can you see why the confliglet is not reporting status for that last check?

**Comment by ErikSchierboom** [comment]
@kotp That's the old configlet workflow. @iHiD could you disable that?

**Comment by kotp** [comment]
Thank you @Auk14HP !

**Pull request merged**
