### PR TITLE
raindrops: add test for 0 as % matches everything on 0

### PR DESCRIPTION
**Pull request by rever0f**
## Why?

So I would guess this exercise should return "0" on 0 input. Only 1 out of 12 responses I reviewed would return this result.

## What?
Added a test to verify a return of  "0" on 0 input.

## How Has This Been Tested?

I ran the test with an exercise that returned "0" and one that returned "PlingPlangPlong" and it errored as appropriate.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds functionality)
- [x] Breaking change (fix or enhancement that would cause existing functionality to change)
- [ ] Gardening (code and/or documentation cleanup)

should only break test results.

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change relies on a pending issue/pull request
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

If this test performs as expected should I update book keeping to a new version?

### CODE REVIEW

**Comment by Insti** [comment]
Thanks @rever0f.

The common test data for this problem comes from the https://github.com/exercism/problem-specifications repository,  could you open an issue there to discuss whether adding a test for zero is appropriate and what the expected value should be.

I believe zero has infinitely many factors so "PlingPlangPlong" would be the correct output.
But my math knowledge is a bit rusty. Why do you thing "0" is the desired result here?

**Comment by Insti** [comment]
https://math.stackexchange.com/questions/776627/factors-of-zero

**Comment by rever0f** [comment]
Sorry, thought I'd just looked this up recently and 0 had no factors, but must have been something else. Looking it up now as  far as I can tell the internet consensus is that 0 has infinite factors, which is kind of interesting. Not sure of a definitive source, but good enough for me.

**Comment by Insti** [comment]
No problem. :)

Thanks for opening the Pull Request anyway. :heart:

**Pull request closed without merging**
