### PR TITLE
Set icon for log-line-parser and moviegoer

### PR DESCRIPTION
**Pull request by angelikatyborska**
There is an icon that first the exercise log-line-parser but it's called slightly differently.

### CODE REVIEW

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
@angelikatyborska this could be sqashed and merged, but I think having the two commits would make the final result better.

**Comment by angelikatyborska** [comment]
@kotp I have no merge powers in this repository

**Comment by kotp** [comment]
> @angelikatyborska this could be sqashed and merged, but I think having the two commits would make the final result better.

But it is your PR, you should be able to do the needful and force push the branch.

**Comment by angelikatyborska** [comment]
@kotp Now I'm confused. I interpreted your first statement, this one:

> this could be sqashed and merged, but I think having the two commits would make the final result better.

As "when merging this branch, it should be merged with a merge commit instead of a squash and merge". I'm fine with either, but I do not have the possibility of merging this PR.

Your second statement says something about force-pushing. I don't understand how that relates to the choice between "merge commit" vs "squash and merge". Do you want me to rebase this branch somehow? What do you want me to change?

**Comment by kotp** [comment]
I could merge it, but if you think you can fix the commit history, rebasing on current `main` and do a force push to the PR branch, then it will allow a rebase and merge or even a straight merge.  Right now I could squash and merge, but I would like to have at least the two commits excluding the one that reads "Merge branch 'main' into patch-1".

**Comment by angelikatyborska** [comment]
@kotp here you go

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
Very nice… Thank you.

**Pull request merged**
